name: Fetch House Representative Trading Disclosures

on:
  schedule:
    # Runs at 00:00 UTC on the 15th of every month
    - cron: '0 0 15 * *'
  # Allows manual trigger of the workflow
  workflow_dispatch:

jobs:
  fetch-house-rep:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run house representative disclosure script
      run: python fetch_house_rep.py 